// import "./post"
// import "./get/index"
// import "./intercepters/index"
// import "./transform/transformRequest"
// import "./cancel/index"
// import "./cookie/index"
// import "./xsrf/index"
// import "./upload/index"
import "./auth"
// import "./error"
// import "./extend"